name: knobeltunier_v2
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  material_symbols_icons: ^4.2815.1
  printing: ^5.13.4
  pdf: ^3.11.1
  change_app_package_name: ^1.4.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  file_picker: ^8.1.7
  flutter_blue: ^0.8.0
  window_manager: ^0.4.3
  path_provider: ^2.1.5
  bitsdojo_window: ^0.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.0.0


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

